include("${COMMON}")

set(P "Strings")
# TODO: Some run2 stuff
run("${P} Unknown" "K=V;K;V" "V")
run("${P} simple assingment" "K=Hello;K" "Hello")
run("${P} simple reassingment" "K=V;K=Y;K" "Y")
run("${P} append" "K=V;+K=Y;K" "VY")
run("${P} append with space" "K=V;+K= Y;K" "V Y")
run("${P} remove char" "K=AB;-K=B;K" "A")

set(P "References")
run("${P} 1" "K=V;V=3;$K" "3")
run("${P} 2" "K=V;V=$K;V" "V")
run("${P} 3" "K=V;$K=$K;V" "V")
run("${P} 4" "K=V;Y=$K;Y" "V")
run("${P} 5" "K=V;$K=$K;$K" "V")
run("${P} 6" "V=$K;V" "")

set(P "Matching")
run("${P} 1" "KAI=foo;KAE=bar;~KA;*" "")
run("${P} 2" "KAI=foo;KEE=bar;~KA;*" "KEE=bar")

set(P "Deletion")
run("${P} 1" "FOO=bar;FOO=;*" "")
run("${P} 2" "FOO=bar;~bar;*" "FOO=bar")
run("${P} 3" "FOO=bar;g={\"foo\":1,\"bar\":{\"cow\":3}};~g;*" "FOO=bar")
run("${P} 4" "FOO=bar;~g={\"foo\":1,\"bar\":{\"cow\":3}};*" "FOO=bar")

set(P "Numbers")
run("${P} increment" "K=0;+K" "1")
run("${P} decrement" "K=1;-K" "0")
run("${P} decrement no negative" "K=0;-K" "0")
run("${P} increment by 1" "K=0;+K=1;K" "1")
run("${P} increment by 2" "K=0;+K=2;K" "2")
run("${P} decrement by 4" "K=10;-K=4;K" "6")
run("${P} decrement by 10 no negative" "K=0;-K=10;K" "0")
run("${P} increment something" "K=-1;+K" "1")
run("${P} increment something" "K=-2;+K" "1")
run("${P} compicated something" "K=0;+-+-+K;K" "0x1\n0")
run("${P} increment overflow" "K=18446744073709551615;+K;" "0")
run("${P} increment by negative" "K=2;+K=-1;K" "1")
run("${P} increment by positive" "K=2;+K=+1;K" "3")
run("${P} decrement by positive" "K=2;-K=+1;K" "1")
run("${P} decrement by negative" "K=2;-K=-1;K" "3")
run("${P} something negative" "-0=-0;0" "0")

set(P "Negative")
run("${P} 1" "a=-2;a" "-2")
run("${P} 2" "a=-3;+a" "1")
run("${P} 3" "a=-2;+a=1;a" "1")
run("${P} 4" "a=-2;+a=4;a" "4")
run("${P} 5" "a=0;-a" "0")
run("${P} 6" "a=0;-a=4;a" "0")
run("${P} 7" "a=0;+a=-4;a" "0")
run("${P} 8" "a=1;+a=-4;a" "0")
run("${P} 9" "a=0;-a=4;a" "0")
run("${P} 10" "a=-4;+a=1;a" "1")
run("${P} 11" "a=-4;-a=1;a" "0")
run("${P} 12" "a=-4;+a=-1;a" "0")

set(P "Quoted strings")
run("${P} 1" "c=3;a=\"b;c\";a" "b;c")
run("${P} 2" "c=3;a=\"b\\\"c\";a" "b\"c")

set(P "Types")
run("${P} 1" "c=-1;?c" "number")
run("${P} 2" "c=1;?c" "number")
run("${P} 3" "c=0;?c" "number")
run("${P} 4" "c=a;?c" "string")
run("${P} 5" "c=true;?c" "boolean")
run("${P} 6" "c={\"foo\":1,\"bar\":[1,2,3]};?c" "json")
run("${P} 7" "c=;?c" "undefined")

end()
